import {
  House,
  MagnifyingGlass,
  ShoppingCart,
  User,
  Sun,
  Moon,
  List,
  X,
  ArrowRight,
  ArrowLeft,
  CaretRight,
  CaretDown,
  Heart,
  Storefront,
  Bread,
  BowlFood,
  Package,
  ChartBar,
  ClipboardText,
  Gear,
  SignOut,
  Users,
  Plus,
  Minus,
  Trash,
  PencilSimple,
  Check,
  CheckCircle,
  Clock,
  CookingPot,
  Bag,
  Truck,
  XCircle,
  WarningCircle,
  Envelope,
  Phone,
  MapPin,
  Lock,
  Eye,
  EyeSlash,
  UploadSimple,
  DownloadSimple,
  Star,
  ShareNetwork,
  CreditCard,
  Money,
  ShieldCheck,
  SlidersHorizontal,
  CalendarBlank,
} from "@phosphor-icons/react";

const icons = {
  home: House,
  search: MagnifyingGlass,
  cart: ShoppingCart,
  user: User,
  sun: Sun,
  moon: Moon,
  menu: List,
  close: X,
  arrow: ArrowRight,
  back: ArrowLeft,
  next: CaretRight,
  down: CaretDown,
  heart: Heart,
  store: Storefront,
  bread: Bread,
  meal: BowlFood,
  inventory: Package,
  chart: ChartBar,
  orders: ClipboardText,
  settings: Gear,
  logout: SignOut,
  users: Users,
  plus: Plus,
  minus: Minus,
  trash: Trash,
  edit: PencilSimple,
  check: Check,
  completed: CheckCircle,
  pending: Clock,
  clock: Clock,
  preparing: CookingPot,
  pickup: Bag,
  delivery: Truck,
  cancelled: XCircle,
  warning: WarningCircle,
  email: Envelope,
  phone: Phone,
  location: MapPin,
  lock: Lock,
  eye: Eye,
  hidden: EyeSlash,
  upload: UploadSimple,
  download: DownloadSimple,
  star: Star,
  share: ShareNetwork,
  card: CreditCard,
  cash: Money,
  shield: ShieldCheck,
  filter: SlidersHorizontal,
  calendar: CalendarBlank,
};
export default function Icon({
  name,
  size = 20,
  weight = "regular",
  ...props
}) {
  const Component = icons[name] || Bag;
  return (
    <Component size={size} weight={weight} aria-hidden="true" {...props} />
  );
}
